# Generated by Django 2.0.3 on 2018-11-27 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('snils', models.CharField(max_length=14, unique=True, verbose_name='СНИЛС')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='email')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=80, verbose_name='Фамилия')),
                ('patronimic', models.CharField(blank=True, max_length=80, verbose_name='Отчество')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата Регистрации')),
                ('telephone', models.CharField(blank=True, max_length=18, verbose_name='Номер телефона')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CallDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время вызова')),
                ('temperature', models.CharField(max_length=4, verbose_name='Температура')),
                ('complaints', models.CharField(max_length=1000, verbose_name='Жалобы')),
            ],
        ),
        migrations.CreateModel(
            name='CallDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_doc_site', models.CharField(max_length=50, verbose_name='ID сайта')),
                ('date', models.DateTimeField(verbose_name='Дата обращения')),
                ('temperature', models.CharField(max_length=4, verbose_name='Температура')),
                ('complaints', models.CharField(max_length=1000, verbose_name='Жалобы')),
                ('kladr', models.CharField(max_length=17, verbose_name='КЛАДР')),
                ('house', models.CharField(max_length=10, verbose_name='Дом')),
                ('room', models.CharField(blank=True, max_length=10, verbose_name='Квартира')),
                ('add_inform', models.CharField(blank=True, max_length=1000, verbose_name='Доп.Информация')),
                ('status_send', models.CharField(max_length=10, verbose_name='Статус отправки')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата обращения')),
                ('id_doc_site', models.CharField(max_length=50, verbose_name='ID сайта')),
                ('recipient', models.CharField(blank=True, max_length=50, verbose_name='Кому обращение')),
                ('subject', models.CharField(max_length=50, verbose_name='Тема сообщения')),
                ('message', models.CharField(max_length=100, verbose_name='Сообщение')),
                ('status_send', models.CharField(max_length=10, verbose_name='Статус отправки')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя опекаемого')),
                ('surname', models.CharField(max_length=80, verbose_name='Фамилия опекаемого')),
                ('patronimic', models.CharField(max_length=80, verbose_name='Отчество опекаемого')),
                ('snils', models.CharField(max_length=14, verbose_name='СНИЛС опекаемого')),
                ('date_born', models.DateField(verbose_name='Дата Рождения')),
                ('trustee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='calldoctor',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountpage.Patient'),
        ),
        migrations.AddField(
            model_name='calldoctor',
            name='trustee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calldoc',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountpage.Patient'),
        ),
        migrations.AddField(
            model_name='calldoc',
            name='trustee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
