# Generated by Django 2.0.3 on 2018-10-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('snils', models.CharField(max_length=14, unique=True, verbose_name='email')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='email')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('patronimic', models.CharField(blank=True, max_length=255, verbose_name='Отчество')),
                ('date_birth', models.DateTimeField(verbose_name='Дата Рождения')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата Регистрации')),
                ('telephone', models.CharField(blank=True, max_length=18, verbose_name='Номер телефона')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
