# Generated by Django 2.0.3 on 2018-11-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldoctor',
            name='patient',
            field=models.CharField(max_length=14, verbose_name='СНИЛС'),
        ),
    ]
