# Generated by Django 2.0.3 on 2018-11-06 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountpage', '0003_remove_patientuser_date_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время вызова')),
                ('temperature', models.CharField(max_length=4, verbose_name='Температура')),
                ('complaints', models.CharField(max_length=1000, verbose_name='Жалобы')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя опекаемого')),
                ('surname', models.CharField(max_length=80, verbose_name='Фамилия опекаемого')),
                ('patronimic', models.CharField(max_length=80, verbose_name='Отчество опекаемого')),
                ('snils', models.CharField(max_length=14, verbose_name='СНИЛС опекаемого')),
                ('date_born', models.DateField(verbose_name='Дата Рождения')),
            ],
        ),
        migrations.AlterField(
            model_name='patientuser',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='patientuser',
            name='patronimic',
            field=models.CharField(blank=True, max_length=80, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='patientuser',
            name='surname',
            field=models.CharField(blank=True, max_length=80, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='patient',
            name='trustee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calldoc',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountpage.Patient'),
        ),
        migrations.AddField(
            model_name='calldoc',
            name='trustee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
