# Generated by Django 2.0.3 on 2018-11-10 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountpage', '0004_auto_20181106_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения')),
                ('id_doc_site', models.CharField(max_length=50, verbose_name='ID сайта')),
                ('recipient', models.CharField(max_length=50, verbose_name='Кому обращение')),
                ('subject', models.CharField(max_length=50, verbose_name='Тема сообщения')),
                ('message', models.CharField(max_length=100, verbose_name='Сообщение')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
