# Generated by Django 2.0.3 on 2018-11-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpage', '0005_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(verbose_name='Дата обращения'),
        ),
    ]
