# Generated by Django 2.0.3 on 2018-11-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpage', '0006_auto_20181112_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status_send',
            field=models.CharField(default=False, max_length=10, verbose_name='Статус отправки'),
            preserve_default=False,
        ),
    ]
