# Generated by Django 2.0.3 on 2018-11-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpage', '0007_message_status_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.CharField(blank=True, max_length=50, verbose_name='Кому обращение'),
        ),
    ]
