# Generated by Django 2.0.3 on 2018-10-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientuser',
            name='date_birth',
            field=models.DateTimeField(blank=True, verbose_name='Дата Рождения'),
        ),
        migrations.AlterField(
            model_name='patientuser',
            name='snils',
            field=models.CharField(max_length=14, unique=True, verbose_name='СНИЛС'),
        ),
    ]
