# Generated by Django 2.0.3 on 2018-10-27 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountpage', '0002_auto_20181027_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientuser',
            name='date_birth',
        ),
    ]
